config/routes.rb
CrowdFunding::Application.routes.draw do

  constraints(:subdomain => ADMIN_SUBDOMAIN) do
    scope :module => "admin" do
      resources :products
      resources :global_admins do
        get "all_admins" ,:on => :collection
        get "ideas" ,    :on=> :collection
        get "slave_admin_group_mgmt" ,    :on=> :collection
        get "main_admin_group_mgmt" ,    :on=> :collection
        get "edit_general_settings",  :on => :member
        put "update_general_settings",  :on => :member
        get :autocomplete_language_name, :on => :collection
        get :autocomplete_user_email, :on => :collection
        get :profile_setting , :on => :collection
        get :edit_integration_setting , :on => :collection
        put :update_integration_setting, :on => :collection
        get :all_workers, :on => :collection
        post :new_user , :on => :collection
      end

      resources :local_admins do
        get "all_users_globally" , :on => :collection
        get "listing_all_the_workers" , :on => :collection
        get "manage_admin_group" , :on => :collection
        get "show_local_admin"  ,:on => :collection
        get "new_local_admin"  ,:on => :collection
        get "new_admin_group"  ,:on => :collection
        get "edit_local_admin",  :on => :member
        put "update_local_admin", :on => :member
        get "show_admin"       , :on => :member
        get :autocomplete_country_detail_name, :on => :collection
        post "admin_group_creation", :on => :collection
        get  "my_settings",        :on => :collection
        put  "update_my_setting",        :on => :collection
        get  "teams_management",        :on => :collection
        get :autocomplete_language_name, :on => :collection
        get :check_for_existing_user  ,  :on => :collection
        get :check_for_existing_user_for_ag  ,  :on => :collection
        get :get_product_details,               :on => :collection
        get :edit_admin_group ,          :on => :member
        put :update_admin_group ,         :on => :member
        get :edit_main_admin_group,      :on => :member
        put :update_main_admin_group,      :on => :member
        get :main_admin_group,              :on => :collection
      end

      as :local_admins do
        match '/local_admins/change_admin_role/:id'   =>'local_admins#change_admin_role',:via => :get    ,:as=>:change_admin_role
        match '/local_admins/create_local_admin'   =>'local_admins#create_local_admin',:via => :post
        match '/local_admins/edit/:id'   =>'local_admins#edit_user_info_from_la',:via => :get ,:as=>:edit_user_info_from_la
        match '/local_admins/canceled_user_account/:id'   =>'local_admins#canceled_user_account_from_la',:via => :get    ,:as=>:canceled_user_account_from_la
        match '/local_admins/update/:id'   =>'local_admins#update_user_info_from_la',:via => :post ,:as=>:update_user_info_from_la
        match '/local_admins/suspend/:id'   =>'local_admins#suspend_user_by_la',:via => :get    ,:as=>:suspend_user_by_la
        match '/local_admins/change_ago_to_mago/:id'   =>'local_admins#change_ago_to_mago',:via => :post    ,:as=>:change_ago_to_mago
        match '/local_admins/show_AGO_for_change_role/:id'   =>'local_admins#show_AGO_for_change_role',:via => :get    ,:as=>:show_AGO_for_change_role

      end

      resources :main_local_admins do
        get "autocomplete_country_detail_name", :on => :collection
      end

      as :main_local_admins do
        match '/main_local_admin/all_users'   =>'main_local_admins#all_users',:via => :get
        match '/main_local_admin/information/:id'   =>'main_local_admins#show_user_to_main_local_admin',:via => :get ,:as=>:show_user_to_main_local_admin
        match '/main_local_admin/edit/:id'   =>'main_local_admins#edit_user_info_mla',:via => :get ,:as=>:edit_user_info_mla
        match '/main_local_admin/update/:id'   =>'main_local_admins#update_user_info_by_mla',:via => :post ,:as=>:update_user_info_by_mla
        match '/main_local_admin/suspend/:id'   =>'main_local_admins#suspend_user_by_mla',:via => :get    ,:as=>:suspend_user_by_mla
        match '/main_local_admin/ideas_belonging_to_users'   =>'main_local_admins#ideas_belonging_to_users',:via => :get
        match '/main_local_admin/change_idea_status_by_mla/:id'   =>'main_local_admins#change_idea_status_by_mla',:via => :get    ,:as=>:change_idea_status_by_mla
        match '/main_local_admin/listing_good_ideas'   =>'main_local_admins#listing_good_ideas',:via => :get
        match '/main_local_admin/listing_projects'   =>'main_local_admins#listing_projects',:via => :get
        match '/main_local_admin/canceled_user_account/:id'   =>'main_local_admins#canceled_user_account',:via => :get    ,:as=>:canceled_user_account

      end
    end
  end

  resources :business_groups do
  collection do
    get :all_workers
    get :new_business_group
    get :autocomplete_language_name
    get :autocomplete_country_detail_name
    get :all_owned_groups
  end
    member do
      get :bg_external_links
      put :update_bg_external_links
      get :bg_location
      put :update_bg_location
      get :bg_publication_settings
      put :update_bg_publication_settings
      post :change_owner
      get :select_worker_change_owner
      get :reset_projects_visibility
      get :reset_group_visibility
      get :team_and_projects_setting
      put :update_team_and_projects_setting
      get :bg_description
      put :update_bg_description
      get :bg_multimedia
      put :update_bg_multimedia
      get :bg_general_setting
      put :update_bg_general_setting
      get :edit_ak
      put :update_ak
      get :edit_publish
      put :update_publish
    end
  end
  resources :main_admin_group_owners do
    get "related_ideas", :on => :collection
    get "change_ownership" , :on => :collection
    put "changed" ,:on => :member
    get "all_workers", :on => :member
  end
  resources :admin_groups do
    get "workers_management" ,:on => :collection
    get "all_my_admin_group_workers" ,:on => :collection
    get "related_ideas", :on => :collection
    get "my_keys", :on=> :collection
    get "show_admin_group", :on => :member
    get "show_main_admin_group", :on => :member
    get "edit_admin_group", :on => :member
    put "update_admin_group", :on=> :member
    get "delete_admin_group", :on => :member
    get "change_admin_group_status", :on => :member
    get "edit_main_admin_group", :on => :member
    put "update_main_admin_group", :on=> :member
    get "sago_home", :on => :member
    get "all_workers", :on => :member
    get "all_users" ,  :on => :collection
    get "create_worker" ,  :on => :collection
    get "country_selection" ,  :on => :collection
    get :autocomplete_language_name, :on => :collection
    get :autocomplete_country_detail_name, :on => :collection
    get :business_group_management, :on => :collection
  end

  resources :admin_group_workers do
    get :activate_or_deactivate_worker, :on=> :member
    get :check_for_existing_user  ,  :on => :collection
    get :my_groups, :on => :collection
  end

  resources :consultant_workers do
    get "change_worker_to_consultant_worker" ,:on => :member
  end

  resources :ideas do
    collection do
      get 'show_good_idea'
      get 'my_own_project'
    end
    member do
      get :make_it_good
      get :decline
      get :reject
    end
  end

  resources :homes do
    collection do
      get 'news_letter'
      post 'persist_news_letter'
      get 'send_news_letter_page'
      post 'send_news_letter'
      get  'get_campaigns'
      get  'show_error_msg'
      get  'resend_varification_mail'
    end

  end

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    match '/user/management'   =>'users#user_management',:via => :get
    match '/user/information/:id'   =>'users#show_user',:via => :get ,:as=>:show_user
    match '/user/edit/:id'   =>'users#edit_user',:via => :get ,:as=>:edit_user
    match '/user/update/:id'   =>'users#update_user',:via => :put ,:as=>:update_user
    match '/user/suspend/:id'   =>'users#suspend_user',:via => :get    ,:as=>:suspend_user
    match '/user/to_worker/:id'   =>'users#to_worker',:via => :get  , :as => :to_worker
    match '/user/to_admin_group_worker/:id'   =>'users#to_admin_group_worker',:via => :get  , :as => :to_AGW
    match '/user/to_business_group_owner/:id'   =>'users#to_business_group_owner',:via => :get  , :as => :to_BGO
    match '/user/canceled_user_account/:id'   =>'users#canceled_user_account',:via => :get    ,:as=>:canceled_user_account
    match '/user/admin_group_list'   =>'users#admin_group_list',:via => :get

  end

  devise_for :users, :scope => "user",
             :controllers => {:omniauth_callbacks => "omniauth_callbacks" ,
                              :sessions => "sessions" ,
                              :confirmations => 'confirmations',
                              :passwords => 'passwords',
                              :registrations => 'registrations'
             }   do
    get "/login", :to => "sessions#new"
    get "/logout", :to => "sessions#destroy"
    get "/autocomplete_country_detail_name" ,:to=>"registrations#autocomplete_country_detail_name"
    get "users/activate_page" , :to => "sessions#activate_page"
    put "users/activation" , :to => "sessions#activation"
    get "/autocomplete_country_detail_name" ,:to=>"sessions#autocomplete_country_detail_name"
  end

  resources :people do
    collection do
      get 'provider_terms_of_service'
      put 'update_provider_terms_of_service'
    end
  end
  resources  :users do
    collection do
      get :business_groups
      get :manage_users
    end

    member do
      get :edit_settings
      put :update_settings
      get :edit_personal_info
      put :update_personal_info
      get :edit_address
      put :update_address
      get :edit_links
      put :update_links
      get :edit_billing_profile

app/helpers/local_admins_helper.rb
module LocalAdminsHelper
end

app/views/admin/local_admins/_admin_group_mgmt_for_local_admin.erb
<%split_array = request.url.split("/") %>

<h4><div class="pull-right" style="margin-bottom: 15px;">
  <% if split_array.include?("manage_admin_group") %>

      <%= link_to "Slave AG Mgmt" ,manage_admin_group_local_admins_path,:style=>"text-decoration: underline;" %> |
  <%else%>
      <%= link_to "Slave AG Mgmt" ,manage_admin_group_local_admins_path %> |
  <%end%>

  <% if split_array.include?("change_ownership") %>

      <%= link_to "Main AG Mgmt" , main_admin_group_local_admins_path,:style=>"text-decoration: underline;" %> |
  <%else%>
      <%= link_to "Main AG Mgmt" , main_admin_group_local_admins_path %> |
  <%end%>

  <% if split_array.include?("add_new_slave_admin_group") %>
      <%= link_to "Add New Slave Admin Group" ,new_admin_group_local_admins_path ,:style=>"text-decoration: underline;" %>
  <%else%>
      <%= link_to "Add New Slave Admin Group" , new_admin_group_local_admins_path  %>
  <%end%>
</h4>

app/views/admin/local_admins/_la_name.html.erb
<% if (@user.present? && @user.profile.present?) %>
    <% fname = @user.profile.first_name %><% lname = @user.profile.last_name  %>


    <!--<div class="control-group">-->
      <!--<label class="control-label" for="input01"><%= label_tag "first_name: "%><span style="color:red"> </span></label>-->
      <!--<div class="controls">-->
        <!--<%= text_field_tag "profile[first_name]", fname,:class=>"input" %>-->
        <!--&lt;!&ndash;<input type="text" class="input-xlarge" id="input01">&ndash;&gt;-->
        <!--<p class="help-block"></p>-->
      <!--</div>-->
    <!--</div>-->

    <!--<div class="control-group">-->
      <!--<label class="control-label" for="input01"><%= label_tag "last_name: "%><span style="color:red"> </span></label>-->
      <!--<div class="controls">-->
        <!--<%= text_field_tag "profile[last_name]",lname,:class=>"input" %>-->
        <!--&lt;!&ndash;<input type="text" class="input-xlarge" id="input01">&ndash;&gt;-->
        <!--<p class="help-block"></p>-->
      <!--</div>-->
       <!--</div>-->
        <div class="control"><b><span> &nbsp  &nbsp  &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp<%=@user.email%></span> <span> &nbsp &nbsp &nbsp <%=@user.profile.first_name%> <span> &nbsp &nbsp &nbsp <%=@user.profile.last_name%> </span></div></b>


<%else%>


    <!--<div class="control-group">-->
      <!--<label class="control-label" for="input01"><%= label_tag "first_name: "%><span style="color:red"> </span></label>-->
      <!--<div class="controls">-->
        <!--<%= text_field_tag "profile[first_name]","",:class=>"input" %>-->
        <!--&lt;!&ndash;<input type="text" class="input-xlarge" id="input01">&ndash;&gt;-->
        <!--<p class="help-block"></p>-->
      <!--</div>-->
    <!--</div>-->

    <!--<div class="control-group">-->
      <!--<label class="control-label" for="input01"><%= label_tag "last_name: "%><span style="color:red"> </span></label>-->
      <!--<div class="controls">-->
        <!--<%= text_field_tag "profile[last_name]","",:class=>"input" %>-->
        <!--&lt;!&ndash;<input type="text" class="input-xlarge" id="input01">&ndash;&gt;-->
        <!--<p class="help-block"></p>-->
      <!--</div>-->
    <!--</div>-->

    <div class="control"><b><span> &nbsp  &nbsp  &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp<%="We will be soon sending the email to #{params[:email]}"%></span>  </b>  </div>
<%end%>

app/views/admin/local_admins/edit_main_admin_group.html.erb
<h1>Edit Master Admin Group</h1>
<%=form_for @admin_group_owner ,:url=>update_main_admin_group_local_admin_path(@admin_group_owner) , :html => { :class => "form-horizontal",:multipart => true} do |f| %>
    <%= fields_for @admin_group do |ag| %>
        <%= fields_for @profile do |p| %>

            <% if @admin_group_owner.errors.any? || @profile.errors.any? || @admin_group.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@admin_group_owner.errors.count + @profile.errors.count + @admin_group.errors.count , "error") %> prohibited this Admin Group from being saved:</h2>

                  <ul>
                    <% @admin_group_owner.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                    <% @admin_group.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                    <% @profile.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <div class="control-group">
              <label class="control-label" for="input01">AG Owner: </label>
              <div class="controls">
                <%=@profile.first_name%> &nbsp <%=@profile.last_name%> &nbsp &nbsp  <%=@admin_group_owner.email%>  &nbsp &nbsp <%= link_to "Change Owner" ,"#",:class => "btn btn-danger" %>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"> </p>
              </div>
            </div>

            <h3>AG Group Details</h3>



            <div class="control-group">
              <label class="control-label" for="input01">Admin Group Name: <span style="color:red"> *</span></label>
              <div class="controls">
                <%=ag.text_field :name,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01"> Admin Group Description: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :description,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">AG country: <span style="color:red"> *</span></label>
              <div class="controls">
                <%=ag.autocomplete_field :ag_country ,autocomplete_country_detail_name_local_admins_path,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <td><label class="control-label" for="input01">AG Language: <span style="color:red"> </span></label></td>
              <div class="controls">
                <%=ag.autocomplete_field :language ,autocomplete_language_name_local_admins_path ,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="input01"> Admin Group Email: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :ag_email,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <h3>AG Organization Details</h3>

            <div class="control-group">
              <label class="control-label" for="input01"><%= label_tag "first_name: "%><span style="color:red"> </span></label>
              <div class="controls">
                <%= p.text_field :first_name,:class=>"input" %>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01"><%= label_tag "last_name: "%><span style="color:red"> </span></label>
              <div class="controls">
                <%= p.text_field :last_name,:class=>"input" %>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">Company Name: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :company_name,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="input01">Country: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.autocomplete_field :country ,autocomplete_country_detail_name_local_admins_path,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">City: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :city,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">ZipCode: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :zip_code,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">State: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :state,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">Address: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :address,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">Additional_address: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :additional_address,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">Phone Number: <span style="color:red"> </span></label>
              <div class="controls">
                <%=ag.text_field :phone_number,:class=>"input"%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">Select Product: <span style="color:red"> </span></label>
              <div class="controls">
                <%=select_tag :product,options_for_select( @products.collect{|i| i.platform_product_name} ,@product.platform_product_name)%>
                <!--<input type="text" class="input-xlarge" id="input01">-->
                <p class="help-block"></p>
              </div>
            </div>

            <div id= "products_details">
              <%= render :partial => "product_info" %>
            </div>


            <h3>Special Settings and Promotions</h3>

            <div class="control-group">
              <label class="control-label" for="input01">BG Free Standard Commissions Allowed:<span style="color:red"> </span></label>
              <div class="controls">
                <%= ag.radio_button :bg_free_standard_commissions_allowed, true,:class=>"input"%>  True   </div>
              <div class="controls"> <%=ag.radio_button :bg_free_standard_commissions_allowed, false,:class=>"input"%> false  </div>
              <!--<input type="text" class="input-xlarge" id="input01">-->
              <p class="help-block"></p>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">BG Free pro Commissions Allowed:<span style="color:red"> </span></label>
              <div class="controls">
                <%= ag.radio_button :bg_free_pro_commissions_allowed, true,:class=>"input"%>  True   </div>
              <div class="controls"> <%=ag.radio_button :bg_free_pro_commissions_allowed, false,:class=>"input"%> false  </div>
              <!--<input type="text" class="input-xlarge" id="input01">-->
              <p class="help-block"></p>
            </div>

            <div class="control-group">
              <label class="control-label" for="input01">BG Free Private Commissions Allowed:<span style="color:red"> </span></label>
              <div class="controls">
                <%= ag.radio_button :bg_free_private_commissions_allowed, true,:class=>"input"%>  True   </div>
              <div class="controls"> <%=ag.radio_button :bg_free_private_commissions_allowed, false,:class=>"input"%> false  </div>
              <!--<input type="text" class="input-xlarge" id="input01">-->
              <p class="help-block"></p>
            </div>



            <div class="form-actions">
              <%= f.submit "Update",:class =>"btn btn-primary"  %>
              <a class="btn" href="/">Cancel</a>
              <!--<input type="text" class="input-xlarge"  id="input01">-->
            </div>

        <%end%>
    <%end%>
<%end%>

<%= content_for :head do  %>
    <script type="text/javascript">

        jQuery(function(){



            $("#check").click(function(event){
                event.preventDefault();
                var email = $("#user_email").val()
                $.get("/local_admins/check_for_existing_user_for_ag",{"email" :email},function(k){}
                )
            });

            $("#product").change(function(){
                var  product = $("#product").val()
                $.get("/local_admins/get_product_details",{"product" :product},function(k){}
                )

            });

//            var email = new LiveValidation('user_email',{validMessage:" ",onlyOnSubmit:true});
//            email.add( Validate.Email);
//            email.add(Validate.Presence)

            var group_name = new LiveValidation('admin_group_name',{validMessage:" ",onlyOnSubmit:true});

            group_name.add(Validate.Presence)

            var group_email = new LiveValidation('admin_group_ag_email',{validMessage:" ",onlyOnSubmit:true});

            group_email.add(Validate.Presence)
            group_email.add( Validate.Email);

            var telephone_number = new LiveValidation("admin_group_phone_number",{validMessage:" ",onlyOnSubmit:true});
            telephone_number.add( Validate.Format , { pattern: /[+][0-9]{2} [0-9]{10}/g, failureMessage: "Must be in form +xx xxxxxxxxxx" });


        });
    </script>
<% end %>

app/views/admin/local_admins/listing_all_the_workers.html.erb
<h2>Listing all the Worker</h2>
<table border="1" class="table">
  <thead>
  <tr>
    <th><strong> Email <strong></th>
    <th><strong> Ip Address <strong></th>
    <th><strong> Title <strong></th>
    <th><strong> First Name <strong></th>
    <th><strong> Last Name <strong></th>
    <th><strong> Country <strong></th>
    <!--<th><strong> User Role<strong></th>-->
    <th><strong> Action<strong></th>
  </tr>
  </thead>
  <% @workers.each do |worker| %>
      <%profile= worker.profile.nil? ? Profile.new : worker.profile%>
      <tr>
        <td><%= worker.email %></td>
        <td><%= worker.last_sign_in_ip %></td>
        <td><%= profile.title %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= fetch_county_name(worker) %></td>
        <!--<td> <%#= worker.role %>     </td>-->
        <td>  <%#= link_to "Change to AGO",show_worker_for_change_role_path(worker.id) %>
          <%= link_to "Change to AGO",add_new_slave_admin_group_local_admins_path %>

         </td>

      </tr>

  <% end %>
  </table>

app/views/admin/local_admins/show_AGO_for_change_role.html.erb
<h2>Change to MAGO</h2>
<%= form_for @admin_group,:url=>change_ago_to_mago_path, :html => { :class => "form-horizontal",:multipart => true  } do |f|%>

    <div class="control-group">
      <label class="control-label" for="input01"> Name <span style="color:red"> *</span></label>
      <div class="controls">
        <%=f.text_field :name,:class=>"input"%>
        <!--<input type="text" class="input-xlarge" id="input01">-->
        <p class="help-block"></p>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="input01"> Email <span style="color:red"> *</span></label>
      <div class="controls">
        <%=f.text_field :email,:value=>@selected_user.email,:disabled=>"disabled" ,:class=>"input"%>
        <!--<input type="text" class="input-xlarge" id="input01">-->
        <p class="help-block"></p>
      </div>
    </div>


    <div class="form-actions">
      <%= f.submit :class =>"btn btn-primary"  %>
      <!--<input type="text" class="input-xlarge"  id="input01">-->
    </div>
<% end %>
<%= content_for :head do  %>
    <script type="text/javascript">

        jQuery(function(){
            var admin_group_name = new LiveValidation('admin_group_name',{validMessage:" ",onlyOnSubmit:true});
            admin_group_name.add( Validate.Presence,{failureMessage:" Can't be empty"} );


        });
    </script>
<% end %>

app/views/admin/local_admins/show_local_admin.html.erb
<table border="1" class="table">
  <thead> <tr>
    <th>Email</th>
    <th>Country</th>
    <th>Action</th>
  </tr>
  </thead>

  <% @local_admins.each do |local_admin| %>

      <tr>
        <td><%= local_admin.email %></td>
        <td><%= local_admin.country %></td>
         <td> <%= link_to 'Change to MLA', change_admin_role_path(local_admin), confirm: 'Are you sure?', method: :get %></td>
      </tr>
  <% end %>

</table>

app/views/admin/local_admins/teams_management.html.erb
<div align="right"><ul>
  <h4>

    <%= link_to "Workers" ,"#", :style =>" text-decoration: underline;" %>   |

    <%= link_to "Consultants" ,"#"  %>
  </h4>
</ul>
</div>
  <div>
    <%if @master_admin_group.present?%>
        <ul>
          <% @master_admin_group.each do |admin| %>
              <li>
                <h2> <%= link_to "Main Admin Group" , all_workers_main_admin_group_owner_path(admin)%>     </h2>
              </li>
          <%end%>
        </ul>
    <%end%>
  </div>


<div>
  <%if @admins.present?%>
  <ul>
    <% @admins.each do |admin| %>
    <li>
   <h2> <%= link_to admin.name , all_workers_admin_group_owner_path(admin)%>     </h2>
    </li>
    <%end%>
  </ul>
  <%end%>
</div>