config/routes.rb
CrowdFunding::Application.routes.draw do

  constraints(:subdomain => ADMIN_SUBDOMAIN) do
    scope :module => "admin" do
      resources :products
      resources :global_admins do
        get "all_admins" ,:on => :collection
        get "ideas" ,    :on=> :collection
        get "slave_admin_group_mgmt" ,    :on=> :collection
        get "main_admin_group_mgmt" ,    :on=> :collection
        get "edit_general_settings",  :on => :member
        put "update_general_settings",  :on => :member
        get :autocomplete_language_name, :on => :collection
        get :autocomplete_user_email, :on => :collection
        get :profile_setting , :on => :collection
        get :edit_integration_setting , :on => :collection
        put :update_integration_setting, :on => :collection
        get :all_workers, :on => :collection
        post :new_user , :on => :collection
      end

      resources :local_admins do
        get "all_users_globally" , :on => :collection
        get "listing_all_the_workers" , :on => :collection
        get "manage_admin_group" , :on => :collection
        get "show_local_admin"  ,:on => :collection
        get "new_local_admin"  ,:on => :collection
        get "new_admin_group"  ,:on => :collection
        get "edit_local_admin",  :on => :member
        put "update_local_admin", :on => :member
        get "show_admin"       , :on => :member
        get :autocomplete_country_detail_name, :on => :collection
        post "admin_group_creation", :on => :collection
        get  "my_settings",        :on => :collection
        put  "update_my_setting",        :on => :collection
        get  "teams_management",        :on => :collection
        get :autocomplete_language_name, :on => :collection
        get :check_for_existing_user  ,  :on => :collection
        get :check_for_existing_user_for_ag  ,  :on => :collection
        get :get_product_details,               :on => :collection
        get :edit_admin_group ,          :on => :member
        put :update_admin_group ,         :on => :member
        get :edit_main_admin_group,      :on => :member
        put :update_main_admin_group,      :on => :member
        get :main_admin_group,              :on => :collection
      end

      as :local_admins do
        match '/local_admins/change_admin_role/:id'   =>'local_admins#change_admin_role',:via => :get    ,:as=>:change_admin_role
        match '/local_admins/create_local_admin'   =>'local_admins#create_local_admin',:via => :post
        match '/local_admins/edit/:id'   =>'local_admins#edit_user_info_from_la',:via => :get ,:as=>:edit_user_info_from_la
        match '/local_admins/canceled_user_account/:id'   =>'local_admins#canceled_user_account_from_la',:via => :get    ,:as=>:canceled_user_account_from_la
        match '/local_admins/update/:id'   =>'local_admins#update_user_info_from_la',:via => :post ,:as=>:update_user_info_from_la
        match '/local_admins/suspend/:id'   =>'local_admins#suspend_user_by_la',:via => :get    ,:as=>:suspend_user_by_la
        match '/local_admins/change_ago_to_mago/:id'   =>'local_admins#change_ago_to_mago',:via => :post    ,:as=>:change_ago_to_mago
        match '/local_admins/show_AGO_for_change_role/:id'   =>'local_admins#show_AGO_for_change_role',:via => :get    ,:as=>:show_AGO_for_change_role

      end

      resources :main_local_admins do
        get "autocomplete_country_detail_name", :on => :collection
      end

      as :main_local_admins do
        match '/main_local_admin/all_users'   =>'main_local_admins#all_users',:via => :get
        match '/main_local_admin/information/:id'   =>'main_local_admins#show_user_to_main_local_admin',:via => :get ,:as=>:show_user_to_main_local_admin
        match '/main_local_admin/edit/:id'   =>'main_local_admins#edit_user_info_mla',:via => :get ,:as=>:edit_user_info_mla
        match '/main_local_admin/update/:id'   =>'main_local_admins#update_user_info_by_mla',:via => :post ,:as=>:update_user_info_by_mla
        match '/main_local_admin/suspend/:id'   =>'main_local_admins#suspend_user_by_mla',:via => :get    ,:as=>:suspend_user_by_mla
        match '/main_local_admin/ideas_belonging_to_users'   =>'main_local_admins#ideas_belonging_to_users',:via => :get
        match '/main_local_admin/change_idea_status_by_mla/:id'   =>'main_local_admins#change_idea_status_by_mla',:via => :get    ,:as=>:change_idea_status_by_mla
        match '/main_local_admin/listing_good_ideas'   =>'main_local_admins#listing_good_ideas',:via => :get
        match '/main_local_admin/listing_projects'   =>'main_local_admins#listing_projects',:via => :get
        match '/main_local_admin/canceled_user_account/:id'   =>'main_local_admins#canceled_user_account',:via => :get    ,:as=>:canceled_user_account

      end
    end
  end

  resources :business_groups do
  collection do
    get :all_workers
    get :new_business_group
    get :autocomplete_language_name
    get :autocomplete_country_detail_name
    get :all_owned_groups
  end
    member do
      get :bg_external_links
      put :update_bg_external_links
      get :bg_location
      put :update_bg_location
      get :bg_publication_settings
      put :update_bg_publication_settings
      post :change_owner
      get :select_worker_change_owner
      get :reset_projects_visibility
      get :reset_group_visibility
      get :team_and_projects_setting
      put :update_team_and_projects_setting
      get :bg_description
      put :update_bg_description
      get :bg_multimedia
      put :update_bg_multimedia
      get :bg_general_setting
      put :update_bg_general_setting
      get :edit_ak
      put :update_ak
      get :edit_publish
      put :update_publish
    end
  end
  resources :main_admin_group_owners do
    get "related_ideas", :on => :collection
    get "change_ownership" , :on => :collection
    put "changed" ,:on => :member
    get "all_workers", :on => :member
  end
  resources :admin_groups do
    get "workers_management" ,:on => :collection
    get "all_my_admin_group_workers" ,:on => :collection
    get "related_ideas", :on => :collection
    get "my_keys", :on=> :collection
    get "show_admin_group", :on => :member
    get "show_main_admin_group", :on => :member
    get "edit_admin_group", :on => :member
    put "update_admin_group", :on=> :member
    get "delete_admin_group", :on => :member
    get "change_admin_group_status", :on => :member
    get "edit_main_admin_group", :on => :member
    put "update_main_admin_group", :on=> :member
    get "sago_home", :on => :member
    get "all_workers", :on => :member
    get "all_users" ,  :on => :collection
    get "create_worker" ,  :on => :collection
    get "country_selection" ,  :on => :collection
    get :autocomplete_language_name, :on => :collection
    get :autocomplete_country_detail_name, :on => :collection
    get :business_group_management, :on => :collection
  end

  resources :admin_group_workers do
    get :activate_or_deactivate_worker, :on=> :member
    get :check_for_existing_user  ,  :on => :collection
    get :my_groups, :on => :collection
  end

  resources :consultant_workers do
    get "change_worker_to_consultant_worker" ,:on => :member
  end

  resources :ideas do
    collection do
      get 'show_good_idea'
      get 'my_own_project'
    end
    member do
      get :make_it_good
      get :decline
      get :reject
    end
  end

  resources :homes do
    collection do
      get 'news_letter'
      post 'persist_news_letter'
      get 'send_news_letter_page'
      post 'send_news_letter'
      get  'get_campaigns'
      get  'show_error_msg'
      get  'resend_varification_mail'
    end

  end

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    match '/user/management'   =>'users#user_management',:via => :get
    match '/user/information/:id'   =>'users#show_user',:via => :get ,:as=>:show_user
    match '/user/edit/:id'   =>'users#edit_user',:via => :get ,:as=>:edit_user
    match '/user/update/:id'   =>'users#update_user',:via => :put ,:as=>:update_user
    match '/user/suspend/:id'   =>'users#suspend_user',:via => :get    ,:as=>:suspend_user
    match '/user/to_worker/:id'   =>'users#to_worker',:via => :get  , :as => :to_worker
    match '/user/to_admin_group_worker/:id'   =>'users#to_admin_group_worker',:via => :get  , :as => :to_AGW
    match '/user/to_business_group_owner/:id'   =>'users#to_business_group_owner',:via => :get  , :as => :to_BGO
    match '/user/canceled_user_account/:id'   =>'users#canceled_user_account',:via => :get    ,:as=>:canceled_user_account
    match '/user/admin_group_list'   =>'users#admin_group_list',:via => :get

  end

  devise_for :users, :scope => "user",
             :controllers => {:omniauth_callbacks => "omniauth_callbacks" ,
                              :sessions => "sessions" ,
                              :confirmations => 'confirmations',
                              :passwords => 'passwords',
                              :registrations => 'registrations'
             }   do
    get "/login", :to => "sessions#new"
    get "/logout", :to => "sessions#destroy"
    get "/autocomplete_country_detail_name" ,:to=>"registrations#autocomplete_country_detail_name"
    get "users/activate_page" , :to => "sessions#activate_page"
    put "users/activation" , :to => "sessions#activation"
    get "/autocomplete_country_detail_name" ,:to=>"sessions#autocomplete_country_detail_name"
  end

  resources :people do
    collection do
      get 'provider_terms_of_service'
      put 'update_provider_terms_of_service'
    end
  end
  resources  :users do
    collection do
      get :business_groups
      get :manage_users
    end

    member do
      get :edit_settings
      put :update_settings
      get :edit_personal_info
      put :update_personal_info
      get :edit_address
      put :update_address
      get :edit_links
      put :update_links
      get :edit_billing_profile

app/controllers/admin_groups_controller.rb
class AdminGroupsController < ApplicationController
  before_filter :should_be_AGO
  autocomplete :country_detail, :name
  #autocomplete :user, :email
  autocomplete :language, :name


  def show_admin_group
    @admin_group = AdminGroup.find(params[:id])
    @owner = @admin_group.user
    @profile = @owner.profile

  end

  def edit_admin_group
    @admin_group_owner = User.find params[:id]
    #@la_setting = current_user.la_setting
    @profile = @admin_group_owner.profile
    @admin_group = @admin_group_owner.admin_group
    @product = @admin_group_owner.user_products.first.product
    #@products = Product.where(:type => "Slave")
  end


  def update_admin_group
    @admin_group_owner = User.find params[:id]
    @admin_group = @admin_group_owner.admin_group
    if @admin_group.update_attributes(params[:admin_group])
      redirect_to edit_user_registration_path ,:notice => "Your Settings has been updated Successfully"
    else
      @profile = @admin_group_owner.profile
      @product = @admin_group_owner.user_products.first.product
      #@products = Product.where(:type => "Slave")
      redirect_to :action => :edit_admin_group
    end
  end
  def country_selection
    @countries = CountryDetail.all
  end
  #def all_users
  #  @countries = CountryDetail.all
  #  #for this method we need all the persons that have user role also they dont have LA role to them   also not to show all worker to that AG
  #  my_workers = current_user.admin_group.admin_group_workers.collect{|i| i.user}
  #  all_users = User.get_all_user_for_selected_role("User").select{|i| i.country == params[:country_name] && !(i.has_role("Local Admin"))}
  #  @users = (all_users - my_workers ).paginate(:page => params[:page], :per_page => 10)
  #end
  #
  #def create_worker
  #  ###need to check the unlimited part also
  #  total_allowed = (Product.get_product current_user).get_ag_workers_number
  #  admin_group = current_user.admin_group
  #  remaining = total_allowed - admin_group.admin_group_workers.size  if total_allowed != "unlimited"   # this will gives the remaining number of workers that this AG is allowed to have  calculating this by (total_allowed - current)\
  #  total_selected = 0
  #
  #  # checking how many users are selected ny AGO
  #  (0..9).each_with_index do |i|
  #    if params["value_#{i}".to_sym]=="1"
  #      total_selected = total_selected + 1
  #    end
  #  end
  #
  #  #  if total selected is zero the he can't create the worker
  #  if total_selected == 0
  #    redirect_to all_users_admin_groups_path, :notice => "please select a user"
  #  else
  #
  #    #if he can create unlimited AG then can create all
  #    if total_allowed == "unlimited"
  #      (0..2).each do |i|
  #        if params["value_#{i}".to_sym]=="1"
  #          user = User.find params["id_#{i}".to_sym]
  #          agw = user.admin_group_workers.new
  #          agw.admin_group = admin_group
  #          agw.save
  #          logger.info agw.inspect
  #        end
  #      end
  #      redirect_to all_users_admin_groups_path, :notice => "created"
  #    else
  #      if total_selected <= remaining
  #        (0..2).each do |i|
  #          if params["value_#{i}".to_sym]=="1"
  #            user = User.find params["id_#{i}".to_sym]
  #            agw = user.admin_group_workers.new
  #            agw.admin_group = admin_group
  #            agw.save
  #            logger.info agw.inspect
  #          end
  #        end
  #        redirect_to all_users_admin_groups_path, :notice => "created"
  #
  #      else
  #        redirect_to all_users_admin_groups_path, :notice => "cant create because you are allowed to create #{remaining} worker more "
  #      end
  #    end
  #  end
  #end

  #def sago_home
  #  @admin_group = AdminGroup.find(params[:id])
  #  @admin_group_workers = @admin_group.admin_group_workers
  #  #binding.pry_remote
  #end
  #
  #def all_workers
  #  @admin_group = AdminGroup.find(params[:id])
  #  @workers = @admin_group.admin_group_workers.includes(:user)
  #  #render :json => @admin_group_workers
  #end

  def show_main_admin_group
    @main_admin_group = MainAdminGroup.find(params[:id])
  end

  def edit_main_admin_group
    @admin_group_owner = User.find params[:id]
    #@la_setting = current_user.la_setting
    @profile = @admin_group_owner.profile
    @admin_group = @admin_group_owner.admin_group
    @product = @admin_group_owner.user_products.first.product
    #@products = Product.where(:type => "Mater")
  end

  def update_main_admin_group
    @admin_group_owner = User.find params[:id]
    @admin_group = @admin_group_owner.admin_group
    if @admin_group.update_attributes(params[:admin_group])
      redirect_to edit_user_registration_path ,:notice => "Your Settings has been updated Successfully"
    else
      @profile = @admin_group_owner.profile
      @product = @admin_group_owner.user_products.first.product
      #@products = Product.where(:type => "Master")
      redirect_to :action => :edit_main_admin_group
    end
  end

  def workers_management
    @workers = current_user.admin_group.admin_group_workers.includes(:user)
  end

  def business_group_management
    admin_group = current_user.admin_group
    @business_groups = admin_group.business_groups.includes(:user).paginate(:page => params[:page], :per_page => 10)
    #render :json => @business_groups
  end




  private

  def should_be_AGO
    redirect_to root_path, :notice => "You should have the AGO privileges to perform this action" if !(RolesManager.is_role_present?("Admin Group Owner", current_user))
  end
end

app/views/admin_groups/all_my_admin_group_workers.html.erb
<h1>Upgrade AGW to BGO</h1>


<table border="1" class="table">
  <thead> <tr>
    <th>Email</th>
    <th>Country</th>
    <th>Action</th>
  </tr>
  </thead>

  <% @admin_group_workers.each do |worker| %>

      <tr>
        <td><%= worker.user.email %></td>
        <td><%= worker.user.country %></td>
        <td> <%= link_to 'Change to BGO',to_BGO_path(worker.user)%></td>
      </tr>
  <% end %>

</table>

app/views/admin_groups/all_users.html.erb
<%= form_tag  create_worker_admin_groups_path, :method => :get  do %>
    <%@users.each_with_index do |i,j|%>
        <br>

        <%= text_field_tag "name_#{j}" ,i.email%>
        <%= hidden_field_tag "id_#{j}" ,i._id%>
        <%= check_box_tag("value_#{j}") %>
        <br>
    <% end %>
    <%= will_paginate @users %>
    <%= submit_tag("Search") %>

<% end %>

app/views/admin_groups/all_workers.html.erb
<h2>Listing all the Worker</h2>
<%if @workers.empty?%>
    <h3> This Group currently have no workers</h3>
<%else%>
    <table border="1" class="table">
      <thead>
      <tr>
        <th><strong> Email <strong></th>
        <th><strong> Country <strong></th>
        <!--<th><strong> User Role<strong></th>-->
        <th><strong> Action<strong></th>
      </tr>
      </thead>
      <% @workers.each do |worker|%>

          <%profile= worker.user.profile.nil? ? Profile.new : worker.user.profile%>
          <tr>
            <td><%= worker.user.email %></td>
            <td><%= worker.user.country %></td>
            <!--<td> <%#= worker.role %>     </td>-->
            <td>  <%#= link_to "Change to AGO",show_worker_for_change_role_path(worker.id) %>
              <%= link_to "Show Profile",show_user_to_local_admin_path(worker.user) %>

            </td>

          </tr>

      <% end %>
    </table>
<% end %>

app/views/admin_groups/business_group_management.html.erb
<table border="1" class="table">
  <thead> <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Ownership Actions</th>
    <th>Group Visibility</th>
    <th>Projects Visibility</th>
    <th>Action</th>
  </tr>
  </thead>

  <% @business_groups.each do |bg| %>

      <tr>
        <td><%= bg.user.email %></td>
        <td><%= bg.bg_name %></td>
        <td><%= link_to "Change Owner" ,select_worker_change_owner_business_group_path(bg)  %> </td>
        <%group_status =bg.bg_visibility
          if group_status == "Private"
            group_display = "Public"
            else
              group_display = "Private"
           end
        %>
        <td><%= link_to group_display ,reset_group_visibility_business_group_path(bg)%>   </td>
        <%project_status =bg.project_visibility
          if project_status == "Private"
            project_display = "Public"
          else
            project_display = "Private"
          end
        %>
        <td><%= link_to project_display ,reset_projects_visibility_business_group_path(bg)%>   </td>
        <td><%= link_to "Edit" ,bg_general_setting_business_group_path(bg)%>   </td>
      </tr>
  <% end %>

</table>
<%= will_paginate @business_groups %>
<%= link_to "new group" ,new_business_group_business_groups_path, :class => "btn"%>

app/views/admin_groups/my_keys.html.erb
<h1>keys</h1>

<table border="1" class="table">
  <thead>
  <tr>
    <th>Key</th>
    <th>belongs to type</th>
    <th>belongs to email</th>
  </tr>
  <thead>

  <% @all_related_keys.each do |key| %>

      <tr>
        <td><%= key.key %></td>
        <td> <%if key.admin_group_consultant_worker.present?%>
              <%="Consultant Worker" %>
              <%email=key.admin_group_consultant_worker.consultant_worker.user.email %>
          <% else %>
              <%= "Admin Group Owner" %>
              <%email=key.admin_group.user.email %>
          <%end%>
        </td>
        <td><%= email %></td>
      </tr>
  <% end %>
  </table>

<br />

<%= link_to 'Back', root_path %>

app/views/admin_groups/related_ideas.html.erb
<h1>Ideas</h1>

<table border="1" class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Sub Title</th>
    <th>Introduction</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Affiliation Key</th>
    <th>Status</th>

    <th>Action</th>
  </tr>
  <thead>

  <% @ideas.each do |good_idea| %>

      <tr>
        <td><%= good_idea.title %></td>
        <td><%= good_idea.sub_title %></td>
        <td><%= good_idea.introduction %></td>
        <td><%= good_idea.amount %></td>
        <td><%= good_idea.currency %></td>
        <td><%= good_idea.affiliation_key %></td>
        <td><%= good_idea.type %></td>
        <!--<td><%= image_tag good_idea.big_image_url %></td>-->
        <td> <%= link_to 'Show', idea_path(good_idea) %>

         <%= link_to 'Make it good',make_it_good_idea_path(good_idea) if good_idea.type !="GoodIdea" %>
        <%= link_to 'decline',decline_idea_path(good_idea) %>
        </td>
      </tr>
  <% end %>
  </table>

<br />

<%= link_to 'Back', root_path %>

app/views/admin_groups/sago_home.html.erb
<%= render :partial => 'shared/sago_tab'%>
<h4> <div style="float:left;height:30px;margin-left:440px;">   <%= link_to 'Workers Management',"#", :confirm => 'Under development' %>     </div> </h4>
<h4> <div style="float:left;height:30px;margin-left:20px;">   <%= link_to "Add New Worker" , new_admin_group_workers_admin_group_owner_admin_group_workers_path(@admin_group)  %> </div> </h4>
<h4><div style="float:left;height:30px;margin-left:20px;">    <%= link_to 'Consultant Worker',"#", :confirm => 'Under development' %>  </div></h4>

<table border="1" class="table">
  <thead>
  <tr>

    <th><strong> Sr. No <strong></th>
    <th><strong> Name of the Worker<strong></th>
    <th><strong> Email Id <strong></th>
    <th><strong> Country <strong></th>
    <th><strong> Roles <strong></th>
    <th><strong> Action <strong></th>
    <th><strong> Status <strong></th>
  </tr>
  </thead>

  <% @admin_group_workers.each_with_index do |admin_group_worker,i| %>
      <tr>  <td><%= i+1 %></td>
        <td><%= admin_group_worker.user.profile.to_s %></td>
        <td><%= admin_group_worker.user.email %></td>
        <td><%= admin_group_worker.user.country%></td>
        <td><%= (admin_group_worker.user.get_all_roles - ["User", "Admin Group Owner", "Main Admin Group Owner"]).join(",") %></td>

        <!--<td> <%#= link_to 'View', show_admin_group_admin_group_owner_path(admin_group_worker) %> |-->
        <!--<%#= link_to 'Edit',edit_admin_group_admin_group_owner_path(admin_group_worker) %>-->

        <%#= link_to 'Delete Group',delete_admin_group_admin_group_owner_path(admin_group), confirm: 'Are you sure? you want to delete group', method: :get %>
        <!--<#% change_status_to = admin_group.is_active? ? "Deactivate": "Activate" %>-->
        <!--<%#= link_to change_status_to,change_admin_group_status_admin_group_owner_path(admin_group),confirm: 'Are you sure? you want to change status', method: :get %>-->
        <td>  </td>
        <td>  </td>
        <!--<td><%#= admin_group.is_active? ? "Active": "Deactive" %></td>-->
      </tr>
  <%end %>
</table>

app/views/admin_groups/select_country.html.erb
<%= form_tag  create_worker_admin_groups_path, :method => :get  do %>
    <%= select_tag :country ,options_for_select(@countries.collect{|i| i.name}),:onchange => "this.form.submit();" %>

<% end %>

app/views/admin_groups/show_admin_group.html.erb
<h2> Admin Group</h2>
<div class="form-horizontal">
  <table border="1" style="text-align: left;">

  <!--<strong> Title: </strong>   <%#= profile.title %>           -->


    <tr><td> <strong> AG Creation Date: </strong>  </td> <td> <%=  @admin_group.ag_creation_date %>     </td>  </tr>
    <tr><td> <strong> AG Expiration Date: </strong> </td>   <td><%=  @admin_group.ag_expiration_date %>         </td> </tr>
    <tr> <td><strong> AG Deactivation Date: </strong> </td>  <td> <%=  @admin_group.ag_deactivation_date %>     </td>   </tr>
    <tr> <td><strong> Admin Group Name: </strong> </td>   <td><%=  @admin_group.name %>       </td>      </tr>
    <tr><td> <strong> Admin Group Description: </strong> </td>  <td> <%=  @admin_group.description %>     </td>  </tr>
    <tr><td> <strong> Admin Group Email: </strong></td>   <td> <%=  @admin_group.ag_email %>     </td> </tr>
    <tr><td>  <strong> Status: </strong> </td> <td>  <%=  @admin_group.status %>          </td> </tr>
    <tr> <td><strong> AG Country: </strong></td>  <td>  <%=  @admin_group.country %>    </td></tr>
    <tr> <td><strong> AG Creation Date: </strong> </td>  <td> <%=  @admin_group.ag_creation_date %>   </td> </tr>
    <tr><td> <strong> Language: </strong> </td> <td>  <%=  @admin_group.language %>          </td>  </tr>
    <tr><td> <strong> First Name: </strong> </td> <td>  <%=  @profile.first_name %>   </td> </tr>

    <tr> <td><strong> Last Name: </strong></td>  <td>  <%=  @profile.last_name %>        </td>  </tr>
    <tr><td><strong> Company Name: </strong></td>  <td>  <%=  @admin_group.company_name %>     </td> </tr>
    <tr><td><strong> Country: </strong>  </td> <td> <%=  @admin_group.country %>       </td>  </tr>
    <tr><td><strong> City: </strong> </td>  <td> <%=  @admin_group.city %>           </td> </tr>
    <tr><td><strong> State: </strong></td> <td>   <%=  @admin_group.state %>    </td>     </tr>
    <tr><td><strong> Zip Code: </strong></td> <td>   <%=  @admin_group.zip_code %>      </td>  </tr>
    <tr><td><strong> Address: </strong>   </td> <td><%=  @admin_group.address %>        </td>   </tr>
    <tr><td><strong> Additional Address: </strong></td>  <td>  <%=  @admin_group.additional_address %>    </td></tr>
    <tr><td><strong> phone_number: </strong>  </td> <td> <%=  @admin_group.phone_number %>            </td></tr>


    <tr><td><strong> BG Free Standard Commissions Allowed: </strong> </td>  <td> <%=  @admin_group.bg_free_standard_commissions_allowed %>   </td>  </tr>
    <tr><td><strong> BG  Free Pro Commissions_allowed: </strong>  </td> <td> <%=  @admin_group.bg_free_pro_commissions_allowed %>     </td>  </tr>

    <tr><td><strong> BG Free Private Commissions_allowed: </strong>   </td> <td><%=  @admin_group.bg_free_private_commissions_allowed %>    </td></tr>


    <tr><td><strong> Free Subscription: </strong> </td> <td>  <%=  @admin_group.free_subscription %>   </td></tr>
    <tr><td><strong> Free PaaS Expiration Date:</strong> </td> <td>   <%=  @admin_group.free_paas_expiration_date %>    </tr>


</table>

</div>
<%= link_to 'Back', :back %>

app/views/admin_groups/view_all_workers.html.erb
<h1>Upgrade Workers to AGW</h1>


<table border="1" class="table">
  <thead> <tr>
    <th>Email</th>
    <th>Country</th>
    <th>Action</th>
  </tr>
  </thead>

  <% @workers.each do |worker| %>

      <tr>
        <td><%= worker.email %></td>
        <td><%= worker.country %></td>
        <td> <%= link_to 'Change to AGW',to_AGW_path(worker)%>
          <%= link_to "Change to CW",change_worker_to_consultant_worker_consultant_worker_path(worker.id) %></td>
      </tr>
  <% end %>

</table>

app/views/admin_groups/workers_management.html.erb
<table border="1" class="table">
  <thead> <tr>
    <th>Email</th>
    <th>Country</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  </thead>

  <% @workers.each do |worker| %>

      <tr>
        <td><%= worker.user.email %></td>
        <td><%= worker.user.country %></td>
        <td><%= worker.user.profile.first_name rescue nil %></td>
        <td><%= worker.user.profile.last_name rescue nil%></td>
        <td><%= worker.status%></td>
        <% to_status = "Activate" if worker.status == "Activate" %>
        <% to_status = "Activate" if worker.status == "Deactivate" %>
        <td><%= link_to "Activate" ,activate_or_deactivate_worker_admin_group_worker_path(worker) if worker.status == "Deactive"%>
          <%= link_to "Dectivate" ,activate_or_deactivate_worker_admin_group_worker_path(worker) if worker.status == "Active"%>
        </td>
      </tr>
  <% end %>

</table>
<%= link_to 'Add New Worker',new_admin_group_worker_path, :class => "btn"%>