config/routes.rb
CrowdFunding::Application.routes.draw do

  constraints(:subdomain => ADMIN_SUBDOMAIN) do
    scope :module => "admin" do
      resources :products
      resources :global_admins do
        get "all_admins" ,:on => :collection
        get "ideas" ,    :on=> :collection
        get "slave_admin_group_mgmt" ,    :on=> :collection
        get "main_admin_group_mgmt" ,    :on=> :collection
        get "edit_general_settings",  :on => :member
        put "update_general_settings",  :on => :member
        get :autocomplete_language_name, :on => :collection
        get :autocomplete_user_email, :on => :collection
        get :profile_setting , :on => :collection
        get :edit_integration_setting , :on => :collection
        put :update_integration_setting, :on => :collection
        get :all_workers, :on => :collection
        post :new_user , :on => :collection
      end

      resources :local_admins do
        get "all_users_globally" , :on => :collection
        get "listing_all_the_workers" , :on => :collection
        get "manage_admin_group" , :on => :collection
        get "show_local_admin"  ,:on => :collection
        get "new_local_admin"  ,:on => :collection
        get "new_admin_group"  ,:on => :collection
        get "edit_local_admin",  :on => :member
        put "update_local_admin", :on => :member
        get "show_admin"       , :on => :member
        get :autocomplete_country_detail_name, :on => :collection
        post "admin_group_creation", :on => :collection
        get  "my_settings",        :on => :collection
        put  "update_my_setting",        :on => :collection
        get  "teams_management",        :on => :collection
        get :autocomplete_language_name, :on => :collection
        get :check_for_existing_user  ,  :on => :collection
        get :check_for_existing_user_for_ag  ,  :on => :collection
        get :get_product_details,               :on => :collection
        get :edit_admin_group ,          :on => :member
        put :update_admin_group ,         :on => :member
        get :edit_main_admin_group,      :on => :member
        put :update_main_admin_group,      :on => :member
        get :main_admin_group,              :on => :collection
      end

      as :local_admins do
        match '/local_admins/change_admin_role/:id'   =>'local_admins#change_admin_role',:via => :get    ,:as=>:change_admin_role
        match '/local_admins/create_local_admin'   =>'local_admins#create_local_admin',:via => :post
        match '/local_admins/edit/:id'   =>'local_admins#edit_user_info_from_la',:via => :get ,:as=>:edit_user_info_from_la
        match '/local_admins/canceled_user_account/:id'   =>'local_admins#canceled_user_account_from_la',:via => :get    ,:as=>:canceled_user_account_from_la
        match '/local_admins/update/:id'   =>'local_admins#update_user_info_from_la',:via => :post ,:as=>:update_user_info_from_la
        match '/local_admins/suspend/:id'   =>'local_admins#suspend_user_by_la',:via => :get    ,:as=>:suspend_user_by_la
        match '/local_admins/change_ago_to_mago/:id'   =>'local_admins#change_ago_to_mago',:via => :post    ,:as=>:change_ago_to_mago
        match '/local_admins/show_AGO_for_change_role/:id'   =>'local_admins#show_AGO_for_change_role',:via => :get    ,:as=>:show_AGO_for_change_role

      end

      resources :main_local_admins do
        get "autocomplete_country_detail_name", :on => :collection
      end

      as :main_local_admins do
        match '/main_local_admin/all_users'   =>'main_local_admins#all_users',:via => :get
        match '/main_local_admin/information/:id'   =>'main_local_admins#show_user_to_main_local_admin',:via => :get ,:as=>:show_user_to_main_local_admin
        match '/main_local_admin/edit/:id'   =>'main_local_admins#edit_user_info_mla',:via => :get ,:as=>:edit_user_info_mla
        match '/main_local_admin/update/:id'   =>'main_local_admins#update_user_info_by_mla',:via => :post ,:as=>:update_user_info_by_mla
        match '/main_local_admin/suspend/:id'   =>'main_local_admins#suspend_user_by_mla',:via => :get    ,:as=>:suspend_user_by_mla
        match '/main_local_admin/ideas_belonging_to_users'   =>'main_local_admins#ideas_belonging_to_users',:via => :get
        match '/main_local_admin/change_idea_status_by_mla/:id'   =>'main_local_admins#change_idea_status_by_mla',:via => :get    ,:as=>:change_idea_status_by_mla
        match '/main_local_admin/listing_good_ideas'   =>'main_local_admins#listing_good_ideas',:via => :get
        match '/main_local_admin/listing_projects'   =>'main_local_admins#listing_projects',:via => :get
        match '/main_local_admin/canceled_user_account/:id'   =>'main_local_admins#canceled_user_account',:via => :get    ,:as=>:canceled_user_account

      end
    end
  end

  resources :business_groups do
  collection do
    get :all_workers
    get :new_business_group
    get :autocomplete_language_name
    get :autocomplete_country_detail_name
    get :all_owned_groups
  end
    member do
      get :bg_external_links
      put :update_bg_external_links
      get :bg_location
      put :update_bg_location
      get :bg_publication_settings
      put :update_bg_publication_settings
      post :change_owner
      get :select_worker_change_owner
      get :reset_projects_visibility
      get :reset_group_visibility
      get :team_and_projects_setting
      put :update_team_and_projects_setting
      get :bg_description
      put :update_bg_description
      get :bg_multimedia
      put :update_bg_multimedia
      get :bg_general_setting
      put :update_bg_general_setting
      get :edit_ak
      put :update_ak
      get :edit_publish
      put :update_publish
    end
  end
  resources :main_admin_group_owners do
    get "related_ideas", :on => :collection
    get "change_ownership" , :on => :collection
    put "changed" ,:on => :member
    get "all_workers", :on => :member
  end
  resources :admin_groups do
    get "workers_management" ,:on => :collection
    get "all_my_admin_group_workers" ,:on => :collection
    get "related_ideas", :on => :collection
    get "my_keys", :on=> :collection
    get "show_admin_group", :on => :member
    get "show_main_admin_group", :on => :member
    get "edit_admin_group", :on => :member
    put "update_admin_group", :on=> :member
    get "delete_admin_group", :on => :member
    get "change_admin_group_status", :on => :member
    get "edit_main_admin_group", :on => :member
    put "update_main_admin_group", :on=> :member
    get "sago_home", :on => :member
    get "all_workers", :on => :member
    get "all_users" ,  :on => :collection
    get "create_worker" ,  :on => :collection
    get "country_selection" ,  :on => :collection
    get :autocomplete_language_name, :on => :collection
    get :autocomplete_country_detail_name, :on => :collection
    get :business_group_management, :on => :collection
  end

  resources :admin_group_workers do
    get :activate_or_deactivate_worker, :on=> :member
    get :check_for_existing_user  ,  :on => :collection
    get :my_groups, :on => :collection
  end

  resources :consultant_workers do
    get "change_worker_to_consultant_worker" ,:on => :member
  end

  resources :ideas do
    collection do
      get 'show_good_idea'
      get 'my_own_project'
    end
    member do
      get :make_it_good
      get :decline
      get :reject
    end
  end

  resources :homes do
    collection do
      get 'news_letter'
      post 'persist_news_letter'
      get 'send_news_letter_page'
      post 'send_news_letter'
      get  'get_campaigns'
      get  'show_error_msg'
      get  'resend_varification_mail'
    end

  end

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    match '/user/management'   =>'users#user_management',:via => :get
    match '/user/information/:id'   =>'users#show_user',:via => :get ,:as=>:show_user
    match '/user/edit/:id'   =>'users#edit_user',:via => :get ,:as=>:edit_user
    match '/user/update/:id'   =>'users#update_user',:via => :put ,:as=>:update_user
    match '/user/suspend/:id'   =>'users#suspend_user',:via => :get    ,:as=>:suspend_user
    match '/user/to_worker/:id'   =>'users#to_worker',:via => :get  , :as => :to_worker
    match '/user/to_admin_group_worker/:id'   =>'users#to_admin_group_worker',:via => :get  , :as => :to_AGW
    match '/user/to_business_group_owner/:id'   =>'users#to_business_group_owner',:via => :get  , :as => :to_BGO
    match '/user/canceled_user_account/:id'   =>'users#canceled_user_account',:via => :get    ,:as=>:canceled_user_account
    match '/user/admin_group_list'   =>'users#admin_group_list',:via => :get

  end

  devise_for :users, :scope => "user",
             :controllers => {:omniauth_callbacks => "omniauth_callbacks" ,
                              :sessions => "sessions" ,
                              :confirmations => 'confirmations',
                              :passwords => 'passwords',
                              :registrations => 'registrations'
             }   do
    get "/login", :to => "sessions#new"
    get "/logout", :to => "sessions#destroy"
    get "/autocomplete_country_detail_name" ,:to=>"registrations#autocomplete_country_detail_name"
    get "users/activate_page" , :to => "sessions#activate_page"
    put "users/activation" , :to => "sessions#activation"
    get "/autocomplete_country_detail_name" ,:to=>"sessions#autocomplete_country_detail_name"
  end

  resources :people do
    collection do
      get 'provider_terms_of_service'
      put 'update_provider_terms_of_service'
    end
  end
  resources  :users do
    collection do
      get :business_groups
      get :manage_users
    end

    member do
      get :edit_settings
      put :update_settings
      get :edit_personal_info
      put :update_personal_info
      get :edit_address
      put :update_address
      get :edit_links
      put :update_links
      get :edit_billing_profile

app/controllers/admin/global_admins_controller.rb
class Admin::GlobalAdminsController < ApplicationController
  before_filter :should_be_global_admin
  before_filter :should_not_be_fake_language, :only => [:update_general_settings]
  autocomplete :language, :name

  def all_admins
    ## @admins = User.all.select{|i| i.role == "Local Admin" || i.role == "Main Local Admin"}
    # @admins = User.all.select{|i| RolesManager.is_role_present?("Local Admin", i) || RolesManager.is_role_present?("Main Local Admin", i)}
    # #@is_any_main_local_admin = User.where(:role => "Main Local Admin" ).present?
    # @is_any_main_local_admin = User.get_all_user_for_selected_role "Main Local Admin"
    # logger.info "3333333333333#{@is_any_main_local_admin.inspect}"
    ##now new flow
    @admins = User.get_all_user_for_selected_role "Local Admin"
    #start_debugging
  end

  def ideas
    @ideas = Idea.all
  end

  def edit_general_settings
    @global_admin = User.find(params[:id])
    @global_admin_general_setting = @global_admin.global_admin_general_setting
  end

  def update_general_settings
    @global_admin = User.find(params[:id])
    #binding.remote_pry
    @global_admin_general_setting = @global_admin.global_admin_general_setting
    logger.info "##########{@global_admin_general_setting.inspect}########"
    if @global_admin_general_setting.update_attributes(params[:user][:global_admin_general_setting]) && @global_admin.update_attributes(params[:user])
      redirect_to :back, :notice=>"Successfully Update"
    else
      render :edit_general_settings
    end

    #@global_admin_general_setting.update_attributes(params)
    #@la_setting = @admin.la_setting || @admin.build_la_setting
    #if @admin.update_attributes(params[:user]) && @la_setting.update_attributes(params[:la_setting])
    #  redirect_to :root, :notice => "successfully_updated"
    #else
    #  render :edit_local_admin
    #end

  end

  def profile_setting
   @global_admin = current_user
   logger.info @global_admin.inspect
  end

  def edit_integration_setting
   @global_admin_general_setting = current_user.global_admin_general_setting
  end

  def update_integration_setting
    @global_admin_general_setting = current_user.global_admin_general_setting
   if  @global_admin_general_setting.update_attributes(params[:global_admin_general_setting])
      redirect_to profile_setting_global_admins_path, :notice => "Updated integration Setting"
   end

  end

  def slave_admin_group_mgmt
    @slave_admin_groups = AdminGroup.all.to_a
  end


  def main_admin_group_mgmt
    @main_admin_groups = MainAdminGroup.all.to_a
  end

  def all_workers
    @workers =AdminGroupWorker.includes(:user)
  end
  #def all_main_admin_groups
  #  @groups = MainAdminGroup.all
  #  logger.info @groups.inspect
  #end
  def  should_be_global_admin      #TODO need to move to user model
    unless RolesManager.is_role_present?("Global Admin", current_user)
      redirect_to root_path, :notice => "sorry you are not able to perform this activity"
    end
  end

  def should_not_be_fake_language
    if Language.is_fake ( params[:user][:global_admin_general_setting][:plateform_default_language])
      redirect_to :back , :notice => "Sorry the language you Have selected is not exist"
    end
  end

  def new_user
    @user = User.new(:email => params[:email], :country => params[:country], :is_provider_terms_of_service=> true, :terms_of_service => true)
    if @user.save
      redirect_to manage_users_users_path ,:notice => "Invitation send to user successfully "
    else
      redirect_to manage_users_users_path ,:notice => "The User With This Email Already Exist"
    end
  end
end

app/helpers/admin/global_admins_helper.rb
module Admin::GlobalAdminsHelper
end

app/helpers/global_admins_helper.rb
module GlobalAdminsHelper
end

app/views/admin/global_admins/all_admins.html.erb
<table border="1" class="table">
 <h3><div style="float:right;height:30px;"><%= link_to "Create New LA" ,new_local_admin_local_admins_path%></div></h3>
  <thead> <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Language</th>
    <th>Master</th>
    <th>Master Billing Deviation</th>
    <th>Master Admin Deviation</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  </thead>

  <% @admins.each_with_index do |admin,index| %>

      <tr>
        <!--<td><%=index+1 %></td>-->
        <td><%=admin.la_setting.local_admin_name rescue nil%></td>
        <!--<td><%=admin.email %></td>-->
        <td><%= admin.la_setting.la_country %></td>
        <td><%= admin.la_setting.language %></td>
        <td><%= admin.la_setting.is_master %></td>
        <td><%= admin.la_setting.master_billing_profile_deviation %></td>
        <td><%= admin.la_setting.master_administration_deviation %></td>
        <td><%= admin.la_setting.status %></td>
        <!--<td><%#=admin.role %></td>-->
        <!--<td>-->
          <!--<%if RolesManagement::RolesManager.is_role_present?("Local Admin", admin)%>-->

              <!--<%if @is_any_main_local_admin.present? %>-->
              <!--<%= link_to 'Change to MLA',"#", :confirm => 'Already a MLA exist in system' %>-->
              <!--<%else%>-->
                  <!--<%= link_to 'Change to MLA', change_admin_role_path(admin), confirm: 'Are you sure?', method: :get %>-->
              <!--<%end%>-->
          <!--<%else%>-->
              <!--<%= "Already MLA"%>-->
          <!--<%end%>-->
        <!--</td>-->
        <td> <%= link_to 'View', show_admin_local_admin_path(admin.id) %> |
          <%= link_to 'Edit',edit_local_admin_local_admin_path(admin.id) %>
          |<%= link_to 'Edit Billing Profile',pass_billing_profile_edit_billing_profile_path(admin.la_setting.platform_billing_profile) %> |
          <% link_url_tag = admin.suspended ? "Activate" : "Dactivate"  %>
          <%#= link_to link_url_tag,suspend_user_path(admin.id) %>
          <%# link_url_tag_account = admin.canceled ? "ReOpen" : "Cancel"  %>
          <%#= link_to link_url_tag_account,canceled_user_account_path(admin.id) %>

      </tr>
  <% end %>

</table>

app/views/admin/global_admins/all_workers.html.erb
<table border="1" class="table">
  <thead> <tr>
    <th>Email</th>
    <th>Country</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>AG Email</th>
    <th>LA Email</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  </thead>

  <% @workers.each do |worker| %>

      <tr>
        <td><%= worker.user.email %></td>
        <td><%= worker.user.country %></td>
        <td><%= worker.user.profile.first_name rescue nil %></td>
        <td><%= worker.user.profile.last_name rescue nil%></td>
        <td><%= worker.admin_group.user.email  %></td>
        <td><%= worker.admin_group.la_setting.user.email %></td>
        <td><%= worker.status%></td>
        <% to_status = "Activate" if worker.status == "Activate" %>
        <% to_status = "Activate" if worker.status == "Deactivate" %>
        <td><%= link_to "Activate" ,activate_or_deactivate_worker_admin_group_worker_path(worker) if worker.status == "Deactive"%>
          <%= link_to "Dectivate" ,activate_or_deactivate_worker_admin_group_worker_path(worker) if worker.status == "Active"%>
        </td>
      </tr>
  <% end %>

</table>

app/views/admin/global_admins/ideas.html.erb
<h1>Listing ideas</h1>
<table border="1" class="table">
  <thead> <tr>
    <th>Sr.no</th>
    <th>Title</th>
    <th>Affiliation Key</th>
    <th>User Country</th>
    <th>Status</th>

    <th>Action</th>
    <th>Make It Good</th>
    <th>Reject</th>
  </tr>
  </thead>

  <% @ideas.each_with_index do |idea,index| %>

      <tr>
        <td><%= index+1 %></td>
        <td><%= idea.title %></td>
        <td><%= idea.affiliation_key %></td>
        <td><%= idea.user.country %></td>
        <td><%= idea.type %></td>
        <!--<td><%= image_tag idea.big_image_url %></td>-->

        <td> <%= link_to 'Show', idea_path(idea) %>


            | <%= link_to 'Edit', edit_idea_path(idea) %>


             | <%= link_to 'Destroy', idea, confirm: 'Are you sure?', method: :delete %></td>
        <td><%= link_to 'Make it good',make_it_good_idea_path(idea) if idea.type !="GoodIdea" %>
          <%= "Already Good" if idea.type =="GoodIdea" %>
        </td>

        <td><%= link_to 'Make it Reject',reject_idea_path(idea) if idea.type !="RejectedIdea" %>
          <%= "Already Rejected" if idea.type =="RejectedIdea" %>

        </td>
      </tr>
  <% end %>

</table>

<br />

<%= link_to 'Back', root_path %>

app/views/admin/global_admins/main_admin_group_mgmt.html.erb
<%split_array = request.url.split("/") %>

<h4><div class="pull-right" style="margin-bottom: 15px;">

  <% if split_array.include?("slave_admin_group_mgmt") %>

      <%= link_to "Slave AG Mgmt" ,slave_admin_group_mgmt_global_admins_path,:style=>"text-decoration: underline;" %>  |
  <%else%>
      <%= link_to "Slave AG Mgmt" ,slave_admin_group_mgmt_global_admins_path %>  |
  <%end%>

  <% if split_array.include?("change_ownership") %>

      <%= link_to "Main AG Mgmt" ,main_admin_group_mgmt_global_adminss_path,:style=>"text-decoration: underline;" %>
  <%else%>
      <%= link_to "Main AG Mgmt" ,main_admin_group_mgmt_global_admins_path %>
  <%end%>
  <%#= link_to 'Main AG Mgmt',"#", :confirm => 'Under development' %>
</div></h4>
<table border="1" class="table">
  <thead>
  <tr>
    <!--<th><strong> Email <strong></th>-->
    <!--<th><strong> Ip Address <strong></th>-->
    <!--<th><strong> Title <strong></th>-->
    <!--<th><strong> First Name <strong></th>-->
    <!--<th><strong> Last Name <strong></th>-->
    <!--<th><strong> Country <strong></th>-->
    <!--&lt;!&ndash;<th><strong> User Role<strong></th>&ndash;&gt;-->
    <!--<th><strong> Action<strong></th>-->
    <th><strong> Sr. No <strong></th>
    <th><strong> Name of the Admin Group <strong></th>
    <th><strong> Name of AG Owner <strong></th>
    <th><strong> Email <strong></th>
    <th><strong> Country <strong></th>
    <th><strong> Action <strong></th>
    <th><strong> Status <strong></th>
  </tr>
  </thead>
  <!--<#% @AGOS.each do |ago| %>-->
  <!--<%#profile= ago.profile.nil? ? Profile.new : ago.profile%>-->
  <!--<tr>-->
  <!--<td><%#= ago.email %></td>-->
  <!--<td><%#= ago.last_sign_in_ip %></td>-->
  <!--<td><%#= profile.title %></td>-->
  <!--<td><%#= profile.first_name %></td>-->
  <!--<td><%#= profile.last_name %></td>-->
  <!--<td><%#= fetch_county_name(ago) %></td>-->
  <!--&lt;!&ndash;<td> <%#= ago.role %>     </td>&ndash;&gt;-->
  <!--  <td> <#% if @already_having_mago.blank? %>
                <!--<%#= link_to "Change to MAGO",show_AGO_for_change_role_path(ago.id) %>-->
  <!--<%# else %>-->
  <!--<%#= link_to "Change to MAGO","", confirm: 'This country is already having MAGO', method: :get %>-->
  <!--<%#end%>-->
  <!--</td>-->

  <!--</tr>-->

  <!--<#% end %>-->
  <% @main_admin_groups.each_with_index do |main_admin_group,i| %>
      <tr>  <td><%= i+1 %></td>
        <td><%= main_admin_group.name %></td>
        <td><%= main_admin_group.user.profile.to_s unless main_admin_group.user.blank? %></td>
        <td><%= main_admin_group.admin_group_email%></td>
        <td><%= main_admin_group.user.country unless main_admin_group.user.blank? %></td>
        <td> <%= link_to 'View',show_main_admin_group_admin_group_owner_path(main_admin_group) %> |
          <%#= link_to 'Edit',edit_admin_group_admin_group_owner_path(slave_admin_group) %>
          <%= link_to 'Edit',edit_main_admin_group_admin_group_owner_path(main_admin_group) %>  |
          <%#= link_to 'Delete Group',delete_admin_group_admin_group_owner_path(slave_admin_group), confirm: 'Are you sure? you want to delete group', method: :get %>
          <%= link_to 'Delete Group',"#", :confirm => 'Under development' %> |
          <% change_status_to = main_admin_group.is_active? ? "Deactivate": "Activate" %>
          <%#= link_to change_status_to,change_admin_group_status_admin_group_owner_path(slave_admin_group),confirm: 'Are you sure? you want to change status', method: :get %>
          <%= link_to change_status_to,"#", :confirm => 'Under development' %>
        </td>

        <td><%= main_admin_group.is_active? ? "Active": "Deactive" %></td>
      </tr>
  <%end %>
</table>

app/views/admin/global_admins/profile_setting.html.erb
<%= render :partial=>"/shared/global_admin_settings"%>

<h3>Profile Setting</h3>
<div></div><b> GA Owner</b>  &nbsp &nbsp &nbsp     <%= "#{@global_admin.email}"%>

app/views/admin/global_admins/slave_admin_group_mgmt.html.erb
<%split_array = request.url.split("/") %>

<h4><div class="pull-right" style="margin-bottom: 15px;">

  <% if split_array.include?("slave_admin_group_mgmt") %>

      <%= link_to "Slave AG Mgmt" ,slave_admin_group_mgmt_global_admins_path,:style=>"text-decoration: underline;" %>  |
  <%else%>
      <%= link_to "Slave AG Mgmt" ,slave_admin_group_mgmt_global_admins_path %>  |
  <%end%>

  <!--<#% if split_array.include?("change_ownership") %>-->

      <!--<#%= link_to "Main AG Mgmt" ,main_admin_group_owners_path,:style=>"text-decoration: underline;" %>-->
  <!--<%#else%>-->
      <!--<%#= link_to "Main AG Mgmt" ,main_admin_group_owners_path %>-->
  <!--<%#end%>-->
  <%= link_to 'Main AG Mgmt',"#", :confirm => 'Under development' %>
</div></h4>
<table border="1" class="table">
  <thead>
  <tr>
    <!--<th><strong> Email <strong></th>-->
    <!--<th><strong> Ip Address <strong></th>-->
    <!--<th><strong> Title <strong></th>-->
    <!--<th><strong> First Name <strong></th>-->
    <!--<th><strong> Last Name <strong></th>-->
    <!--<th><strong> Country <strong></th>-->
    <!--&lt;!&ndash;<th><strong> User Role<strong></th>&ndash;&gt;-->
    <!--<th><strong> Action<strong></th>-->
    <th><strong> Sr. No <strong></th>
    <th><strong> Name of the Admin Group <strong></th>
    <th><strong> Name of AG Owner <strong></th>
    <th><strong> Email <strong></th>
    <th><strong> Country <strong></th>
    <th><strong> Action <strong></th>
    <th><strong> Status <strong></th>
  </tr>
  </thead>
  <!--<#% @AGOS.each do |ago| %>-->
  <!--<%#profile= ago.profile.nil? ? Profile.new : ago.profile%>-->
  <!--<tr>-->
  <!--<td><%#= ago.email %></td>-->
  <!--<td><%#= ago.last_sign_in_ip %></td>-->
  <!--<td><%#= profile.title %></td>-->
  <!--<td><%#= profile.first_name %></td>-->
  <!--<td><%#= profile.last_name %></td>-->
  <!--<td><%#= fetch_county_name(ago) %></td>-->
  <!--&lt;!&ndash;<td> <%#= ago.role %>     </td>&ndash;&gt;-->
  <!--  <td> <#% if @already_having_mago.blank? %>
                <!--<%#= link_to "Change to MAGO",show_AGO_for_change_role_path(ago.id) %>-->
  <!--<%# else %>-->
  <!--<%#= link_to "Change to MAGO","", confirm: 'This country is already having MAGO', method: :get %>-->
  <!--<%#end%>-->
  <!--</td>-->

  <!--</tr>-->

  <!--<#% end %>-->
  <% @slave_admin_groups.each_with_index do |slave_admin_group,i| %>
      <tr>  <td><%= i+1 %></td>
        <td><%= slave_admin_group.name %></td>
        <td><%= slave_admin_group.user.profile.to_s unless slave_admin_group.user.blank? %></td>
        <td><%= slave_admin_group.admin_group_email%></td>
        <td><%= slave_admin_group.user.country unless slave_admin_group.user.blank? %></td>
        <td> <%= link_to 'View', show_admin_group_admin_group_owner_path(slave_admin_group) %> |
          <%#= link_to 'Edit',edit_admin_group_admin_group_owner_path(slave_admin_group) %>
          <%= link_to 'Edit',edit_admin_group_admin_group_owner_path(slave_admin_group) %>  |
          <%#= link_to 'Delete Group',delete_admin_group_admin_group_owner_path(slave_admin_group), confirm: 'Are you sure? you want to delete group', method: :get %>
          <%= link_to 'Delete Group',"#", :confirm => 'Under development' %> |
          <% change_status_to = slave_admin_group.is_active? ? "Deactivate": "Activate" %>
          <%#= link_to change_status_to,change_admin_group_status_admin_group_owner_path(slave_admin_group),confirm: 'Are you sure? you want to change status', method: :get %>
          <%= link_to change_status_to,"#", :confirm => 'Under development' %>
        </td>

        <td><%= slave_admin_group.is_active? ? "Active": "Deactive" %></td>
      </tr>
  <%end %>
</table>