config/routes.rb
CrowdFunding::Application.routes.draw do

  constraints(:subdomain => ADMIN_SUBDOMAIN) do
    scope :module => "admin" do
      resources :products
      resources :global_admins do
        get "all_admins" ,:on => :collection
        get "ideas" ,    :on=> :collection
        get "slave_admin_group_mgmt" ,    :on=> :collection
        get "main_admin_group_mgmt" ,    :on=> :collection
        get "edit_general_settings",  :on => :member
        put "update_general_settings",  :on => :member
        get :autocomplete_language_name, :on => :collection
        get :autocomplete_user_email, :on => :collection
        get :profile_setting , :on => :collection
        get :edit_integration_setting , :on => :collection
        put :update_integration_setting, :on => :collection
        get :all_workers, :on => :collection
        post :new_user , :on => :collection
      end

      resources :local_admins do
        get "all_users_globally" , :on => :collection
        get "listing_all_the_workers" , :on => :collection
        get "manage_admin_group" , :on => :collection
        get "show_local_admin"  ,:on => :collection
        get "new_local_admin"  ,:on => :collection
        get "new_admin_group"  ,:on => :collection
        get "edit_local_admin",  :on => :member
        put "update_local_admin", :on => :member
        get "show_admin"       , :on => :member
        get :autocomplete_country_detail_name, :on => :collection
        post "admin_group_creation", :on => :collection
        get  "my_settings",        :on => :collection
        put  "update_my_setting",        :on => :collection
        get  "teams_management",        :on => :collection
        get :autocomplete_language_name, :on => :collection
        get :check_for_existing_user  ,  :on => :collection
        get :check_for_existing_user_for_ag  ,  :on => :collection
        get :get_product_details,               :on => :collection
        get :edit_admin_group ,          :on => :member
        put :update_admin_group ,         :on => :member
        get :edit_main_admin_group,      :on => :member
        put :update_main_admin_group,      :on => :member
        get :main_admin_group,              :on => :collection
      end

      as :local_admins do
        match '/local_admins/change_admin_role/:id'   =>'local_admins#change_admin_role',:via => :get    ,:as=>:change_admin_role
        match '/local_admins/create_local_admin'   =>'local_admins#create_local_admin',:via => :post
        match '/local_admins/edit/:id'   =>'local_admins#edit_user_info_from_la',:via => :get ,:as=>:edit_user_info_from_la
        match '/local_admins/canceled_user_account/:id'   =>'local_admins#canceled_user_account_from_la',:via => :get    ,:as=>:canceled_user_account_from_la
        match '/local_admins/update/:id'   =>'local_admins#update_user_info_from_la',:via => :post ,:as=>:update_user_info_from_la
        match '/local_admins/suspend/:id'   =>'local_admins#suspend_user_by_la',:via => :get    ,:as=>:suspend_user_by_la
        match '/local_admins/change_ago_to_mago/:id'   =>'local_admins#change_ago_to_mago',:via => :post    ,:as=>:change_ago_to_mago
        match '/local_admins/show_AGO_for_change_role/:id'   =>'local_admins#show_AGO_for_change_role',:via => :get    ,:as=>:show_AGO_for_change_role

      end

      resources :main_local_admins do
        get "autocomplete_country_detail_name", :on => :collection
      end

      as :main_local_admins do
        match '/main_local_admin/all_users'   =>'main_local_admins#all_users',:via => :get
        match '/main_local_admin/information/:id'   =>'main_local_admins#show_user_to_main_local_admin',:via => :get ,:as=>:show_user_to_main_local_admin
        match '/main_local_admin/edit/:id'   =>'main_local_admins#edit_user_info_mla',:via => :get ,:as=>:edit_user_info_mla
        match '/main_local_admin/update/:id'   =>'main_local_admins#update_user_info_by_mla',:via => :post ,:as=>:update_user_info_by_mla
        match '/main_local_admin/suspend/:id'   =>'main_local_admins#suspend_user_by_mla',:via => :get    ,:as=>:suspend_user_by_mla
        match '/main_local_admin/ideas_belonging_to_users'   =>'main_local_admins#ideas_belonging_to_users',:via => :get
        match '/main_local_admin/change_idea_status_by_mla/:id'   =>'main_local_admins#change_idea_status_by_mla',:via => :get    ,:as=>:change_idea_status_by_mla
        match '/main_local_admin/listing_good_ideas'   =>'main_local_admins#listing_good_ideas',:via => :get
        match '/main_local_admin/listing_projects'   =>'main_local_admins#listing_projects',:via => :get
        match '/main_local_admin/canceled_user_account/:id'   =>'main_local_admins#canceled_user_account',:via => :get    ,:as=>:canceled_user_account

      end
    end
  end

  resources :business_groups do
  collection do
    get :all_workers
    get :new_business_group
    get :autocomplete_language_name
    get :autocomplete_country_detail_name
    get :all_owned_groups
  end
    member do
      get :bg_external_links
      put :update_bg_external_links
      get :bg_location
      put :update_bg_location
      get :bg_publication_settings
      put :update_bg_publication_settings
      post :change_owner
      get :select_worker_change_owner
      get :reset_projects_visibility
      get :reset_group_visibility
      get :team_and_projects_setting
      put :update_team_and_projects_setting
      get :bg_description
      put :update_bg_description
      get :bg_multimedia
      put :update_bg_multimedia
      get :bg_general_setting
      put :update_bg_general_setting
      get :edit_ak
      put :update_ak
      get :edit_publish
      put :update_publish
    end
  end
  resources :main_admin_group_owners do
    get "related_ideas", :on => :collection
    get "change_ownership" , :on => :collection
    put "changed" ,:on => :member
    get "all_workers", :on => :member
  end
  resources :admin_groups do
    get "workers_management" ,:on => :collection
    get "all_my_admin_group_workers" ,:on => :collection
    get "related_ideas", :on => :collection
    get "my_keys", :on=> :collection
    get "show_admin_group", :on => :member
    get "show_main_admin_group", :on => :member
    get "edit_admin_group", :on => :member
    put "update_admin_group", :on=> :member
    get "delete_admin_group", :on => :member
    get "change_admin_group_status", :on => :member
    get "edit_main_admin_group", :on => :member
    put "update_main_admin_group", :on=> :member
    get "sago_home", :on => :member
    get "all_workers", :on => :member
    get "all_users" ,  :on => :collection
    get "create_worker" ,  :on => :collection
    get "country_selection" ,  :on => :collection
    get :autocomplete_language_name, :on => :collection
    get :autocomplete_country_detail_name, :on => :collection
    get :business_group_management, :on => :collection
  end

  resources :admin_group_workers do
    get :activate_or_deactivate_worker, :on=> :member
    get :check_for_existing_user  ,  :on => :collection
    get :my_groups, :on => :collection
  end

  resources :consultant_workers do
    get "change_worker_to_consultant_worker" ,:on => :member
  end

  resources :ideas do
    collection do
      get 'show_good_idea'
      get 'my_own_project'
    end
    member do
      get :make_it_good
      get :decline
      get :reject
    end
  end

  resources :homes do
    collection do
      get 'news_letter'
      post 'persist_news_letter'
      get 'send_news_letter_page'
      post 'send_news_letter'
      get  'get_campaigns'
      get  'show_error_msg'
      get  'resend_varification_mail'
    end

  end

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    match '/user/management'   =>'users#user_management',:via => :get
    match '/user/information/:id'   =>'users#show_user',:via => :get ,:as=>:show_user
    match '/user/edit/:id'   =>'users#edit_user',:via => :get ,:as=>:edit_user
    match '/user/update/:id'   =>'users#update_user',:via => :put ,:as=>:update_user
    match '/user/suspend/:id'   =>'users#suspend_user',:via => :get    ,:as=>:suspend_user
    match '/user/to_worker/:id'   =>'users#to_worker',:via => :get  , :as => :to_worker
    match '/user/to_admin_group_worker/:id'   =>'users#to_admin_group_worker',:via => :get  , :as => :to_AGW
    match '/user/to_business_group_owner/:id'   =>'users#to_business_group_owner',:via => :get  , :as => :to_BGO
    match '/user/canceled_user_account/:id'   =>'users#canceled_user_account',:via => :get    ,:as=>:canceled_user_account
    match '/user/admin_group_list'   =>'users#admin_group_list',:via => :get

  end

  devise_for :users, :scope => "user",
             :controllers => {:omniauth_callbacks => "omniauth_callbacks" ,
                              :sessions => "sessions" ,
                              :confirmations => 'confirmations',
                              :passwords => 'passwords',
                              :registrations => 'registrations'
             }   do
    get "/login", :to => "sessions#new"
    get "/logout", :to => "sessions#destroy"
    get "/autocomplete_country_detail_name" ,:to=>"registrations#autocomplete_country_detail_name"
    get "users/activate_page" , :to => "sessions#activate_page"
    put "users/activation" , :to => "sessions#activation"
    get "/autocomplete_country_detail_name" ,:to=>"sessions#autocomplete_country_detail_name"
  end

  resources :people do
    collection do
      get 'provider_terms_of_service'
      put 'update_provider_terms_of_service'
    end
  end
  resources  :users do
    collection do
      get :business_groups
      get :manage_users
    end

    member do
      get :edit_settings
      put :update_settings
      get :edit_personal_info
      put :update_personal_info
      get :edit_address
      put :update_address
      get :edit_links
      put :update_links
      get :edit_billing_profile

app/views/shared/_admin_group_owner_layout.html.erb
<li>
  <a href="<%= related_ideas_admin_group_owners_path %>">Ideas</a>
</li>

<li>
  <a href="<%= view_all_workers_admin_group_owners_path %>">all workers</a>
</li>
<li>
  <a href="<%= all_my_admin_group_workers_admin_group_owners_path %>">all  Admin Group workers</a>
</li>
<li>
  <a href="<%= my_keys_admin_group_owners_path %>">Keys</a>
</li>

app/views/shared/_ag_layout.erb
<%= link_to "Workers Management" ,workers_management_admin_groups_path%>  ||
<%#= link_to "new_window_type_bg" ,new_business_group_business_groups_path%>
<%= link_to "BG management" , business_group_management_admin_groups_path %>

app/views/shared/_bgo_layout.html.erb
<ul class="nav">
  <li>
   <%= link_to "My Owned Business Groups" , all_owned_groups_business_groups_path%>
  </li>
</ul>

app/views/shared/_business_group_owner_layout.html.erb
<li>
  <a href="<%= related_ideas_business_groups_path %>">Ideas</a>
</li>
<li>
  <a href="<%= my_keys_business_groups_path %>">Key</a>
</li>

app/views/shared/_form_errors.html.erb
<% if object.present?%>
<% if object.errors.any?%>
<div class="alert alert-error">

  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<% end %>

app/views/shared/_global_admin_layout.html.erb
  <!--<li>-->
    <!--<a href="<%= all_admins_global_admins_path%>">Admin Management</a>-->
  <!--</li>-->
  <!--<li>-->
    <!--<a href="<%= new_local_admin_local_admins_path %>">New LocalAdmin</a>-->
  <!--</li>-->
  <!--<li>-->
    <!--<a href="<%= ideas_global_admins_path %>">Ideas</a>-->
  <!--</li>-->


  <li> <a href="#">Overview</a></li>
  <%split_array = request.url.split("/") %>
  <% if split_array.include?("edit") or split_array.include?("edit_general_settings") %>
  <li class= "active">
   <%else%>
     <li>
     <%end%>
    <a href="<%= profile_setting_global_admins_path %>">Setting</a>
  </li>
  <% if split_array.include?("all_admins") or split_array.include?("new_local_admin") or split_array.include?("edit_local_admin") or split_array.include?("show_admin")%>
      <li class= "active">
  <%else%>
      <li>
  <%end%>
    <a href="<%= all_admins_global_admins_path %>">Local Admins <br>Management</a>
  </li>
  <% if split_array.include?("slave_admin_group_mgmt") or split_array.include?("edit_main_admin_group") or split_array.include?("main_admin_group_mgmt") %>
      <li class= "active">
  <%else%>
      <li>
  <%end%>
    <a href="<%#=slave_admin_group_mgmt_global_admins_path  %>">Admin Groups  <br>Management</a>
  </li>

  <li>
    <a href="#">Business Groups <br> Management</a>
  </li>
  <!--<li>-->
    <!--<a href="#">Workers <br> Management</a>-->
  <!--</li>-->
  <li>
    <a href="<%= all_workers_global_admins_path %>">Workers <br> Management</a>
  </li>
  <li>
    <a  href="<%= manage_users_users_path %>">Users <br> Management</a>
  </li>
  <% if split_array.include?("ideas")  %>
      <li class= "active">
  <%else%>
      <li>
  <%end%>
    <a href="<%= ideas_global_admins_path  %>">Projects  <br>Management</a>
  </li>
  <li>
    <a href="#">Pages  <br>Management</a>
  </li>
  <li>
    <a href="#">Statistics</a>
  </li>

  <!--<li>-->
    <!--<a href="<%= ideas_global_admins_path  %>">Idea Management</a>-->
  <!--</li>-->

app/views/shared/_global_admin_settings.html.erb
<div ><ul>
  <%split_array = request.url.split("/") %>
  <% if split_array.include?("edit") %>
      <%= link_to 'Profile',profile_setting_global_admins_path ,:style=>"text-decoration: underline;" %>    |
      <%= link_to 'General Settings',edit_general_settings_global_admin_path(current_user) %>   |
  <%else  %>
      <%= link_to 'Profile', profile_setting_global_admins_path  %>    |
      <%= link_to 'General Settings',edit_general_settings_global_admin_path(current_user) %>   |
  <%end%>

  <%= link_to 'Commission Settings',"#", :confirm => 'Under development' %>     |
  <%= link_to 'PaaS Settings',"#" %>     |
  <%= link_to 'Products Setting',products_path %>  |
  <%= link_to 'Integration', edit_integration_setting_global_admins_path %>

</ul>
</div>

app/views/shared/_local_admin_layout.html.erb
<!--<li>-->
<!--<a href="<%#= user_management_path %>">User Management</a>-->
<!--</li>-->

<!--<li>-->
  <!--<a href="<%#= listing_all_the_workers_local_admins_path %>">Admin Group Management</a>-->
<!--</li>-->

<!--<li>-->
  <!--<a href="<%#= listing_all_the_agos_local_admins_path %>">Listing AGOS </a>-->
<!--</li>-->
<!--<li>-->
  <!--<a href="<%#= all_users_globally_local_admins_path %>">upgrade users to worker</a>-->
<!--</li>-->

<%split_array = request.url.split("/") %>
<li> <a href="#">Overview</a></li>
<%split_array = request.url.split("/") %>
<% if split_array.include?("edit") or split_array.include?("my_settings") %>
    <li class= "active">
<%else%>
    <li>
<%end%>
<a href="<%= edit_user_registration_path %>">Setting</a>
</li>

<% if split_array.include?("manage_admin_group") or split_array.include?("change_ownership") or split_array.include?("add_new_slave_admin_group")%>
    <li class= "active">
<%else%>
    <li>
<%end%>
<a href="<%= manage_admin_group_local_admins_path  %>">Admin Group  <br>Management</a></li>

<li>
  <a href="#">Business Groups <br> Management</a>
</li>
<% if split_array.include?("teams_management") %>
    <li class= "active">
<%else%>
    <li>
<%end%>
  <a href="<%#= teams_management_local_admins_path%>">Teams <br> Management</a>
</li>
<li>
  <a href="#">Users <br> Management</a>
</li>
<% if split_array.include?("ideas")  %>
    <li class= "active">
<%else%>
    <li>
<%end%>
<a href="<%= ideas_global_admins_path  %>">Projects  <br>Management</a>
</li>
<li>
  <a href="#">Statistics</a>
</li>

<!--<li>-->
<!--<a href="<%= ideas_global_admins_path  %>">Idea Management</a>-->
<!--</li>-->







<!--
<li>
  <a href="<%#= local_admins_ideas_belonging_to_country_users_path %>">All Ideas</a>
</li>
<li>
  <a href="<%#= local_admins_listing_good_ideas_path %>">All Good Ideas</a>
</li>
<li>
  <a href="<%#= local_admins_listing_projects_path %>">All Projects</a>
</li>-->

app/views/shared/_local_admin_settings.html.erb
<div align="right"><ul>

  <h4>
    <%split_array = request.url.split("/") %>
    <% if split_array.include?("my_settings") %>
        <%= link_to 'General Settings',my_settings_local_admins_path ,:style=>"text-decoration: underline;" %>   |
        <%= link_to 'Profile Settings',edit_user_registration_path  %>
    <%else  %>
        <%= link_to 'General Settings',my_settings_local_admins_path  %>   |
        <%= link_to 'Profile Settings',edit_user_registration_path ,:style=>"text-decoration: underline;" %>
    <%end%>
  </h4>
</ul>
</div>

app/views/shared/_main_local_admin_layout.html.erb
<li>
<a href="<%= main_local_admin_all_users_path %>">All Users</a>
</li>
<!--
<li>
<a href="<%#= main_local_admin_ideas_belonging_to_users_path %>">All Ideas</a>
</li>
<li>
  <a href="<%#= main_local_admin_listing_good_ideas_path %>">All Good Ideas</a>
</li>
<li>
  <a href="<%#= main_local_admin_listing_projects_path %>">All Projects</a>
</li>         -->

app/views/shared/_side_menus_for_bg_create_edit.html.erb
<div class="sidebar-nav">
  <ul class="nav nav-tabs nav-stacked">

    <% if @business_group.present? %>
        <li><%=link_to "General Setting" ,bg_general_setting_business_group_path(@business_group,:edit_bg => true) %></li>
        <li><%=link_to "Publication Options" ,bg_publication_settings_business_group_path(@business_group,:edit_bg => true) %></li>
        <li><%=link_to "Team And Workspace" ,team_and_projects_setting_business_group_path(@business_group,:edit_bg => true) %></li>
        <li> <%=link_to "Links" ,bg_external_links_business_group_path(@business_group,:edit_bg => true) %></li>
        <li> <%=link_to "Locations" ,bg_location_business_group_path(@business_group,:edit_bg => true) %></li>
        <li><%=link_to "Descriptions" ,bg_description_business_group_path(@business_group,:edit_bg => true) %>  </li>
        <li>  <%=link_to "Images And Multimedia " ,bg_multimedia_business_group_path(@business_group,:edit_bg => true) %></li>
    <% end %>

  </ul>
</div >

app/views/shared/_user_layout.html.erb
<%split_array = request.url.split("/") %>
<% if split_array.include?("new")  %>
    <li class= "active">
<%else%>
    <li>
<%end%>
<a href="<%= new_idea_path %>">Propose Idea</a>
</li>
<% if request.path == "/ideas" %>
    <li class= "active">
<%else%>
    <li>
<%end%>
<a href="<%= ideas_path %>">My Ideas</a>
</li>
<% if split_array.include?("show_good_idea")  %>
    <li class= "active">
<%else%>
    <li>
<%end%>
<a href="<%= show_good_idea_ideas_path %>">My Good Ideas</a>
</li>
<li>
  <%= link_to  "Business Groups" ,business_groups_users_path %>
</li>

<li>
  <% if !(current_user.profile.present?)%>
      <a href="<%=  new_profile_path %>">Create Profile</a>
  <%else%>
      <a href="<%=  edit_profile_path(current_user) %>">Edit Profile</a>
  <%end%>
</li>

<li>
  <% if !(current_user.default_billing_profile.present?)%>
      <a href="<%=  new_default_billing_profile_path %>">Create Default Billing Profile</a>
  <%else%>
      <a href="<%=  edit_default_billing_profile_path(current_user) %>">Edit Default Billing Profile</a>
  <%end%>
</li>

app/views/shared/_user_tabs.html.erb
<!--<div><ul>-->
  <!--<h4>      <%= link_to 'Summary',"#", :confirm => 'Under development' %>   |-->
    <!--<% if RolesManagement::RolesManager.is_role_present?("Admin Group Owner",current_user)%>-->
        <!--<a href="<%= user_admin_group_list_path %>">Admin Group List</a>  |-->

    <!--<%end%>-->
    <!--<% if RolesManagement::RolesManager.is_role_present?("Admin Group Worker",current_user)%>-->

        <%= link_to 'Worker',"#", :confirm => 'Under development' %>

    <!--<%end%>-->
    <!--<% if RolesManagement::RolesManager.is_role_present?("Business Group Owner",current_user)%>-->

        <%#= link_to 'BGO',"#", :confirm => 'Under development' %>

  <!--<%end%>-->
    <!--<% if RolesManagement::RolesManager.is_role_present?("Consultant Worker",current_user)%>-->
        <%= link_to 'Consultant',"#", :confirm => 'Under development' %> |


    <!--<%end%>-->

    <!--<% if current_user.profile.present? %>-->
        <!--<a href="<%= edit_profile_path(current_user.profile) %>">Edit Profile</a>   |-->
    <!--<%else %>-->
        <!--<a href="<%= new_profile_path %>">Create Profile</a>     |-->
    <!--<% end %>-->

    <!--<%= link_to "Settings" , edit_user_registration_path  %>-->
  <!--</h4>-->
<!--</ul>-->
<!--</div>-->

app/views/shared/_worker_layout.html.erb
<ul class="nav">
  <li>
    <%= link_to "my_groups", my_groups_admin_group_workers_path%>
  </li>


</ul>